UnitSet["Legacy"]={
	
 DeclareUnit["15degC_BTU", Unit[1054.804,"Joule"],  TraditionalLabel -> "BTU15", CreateSymbol -> False], (**)
 DeclareUnit["15degC_calorie", Unit[4.1855, "Joule"],   TraditionalLabel -> "cal15", CreateSymbol -> False], (**)
 DeclareUnit["20degC_calorie", Unit[4.182, "Joule"],   TraditionalLabel -> "cal20", CreateSymbol -> False], (**)
 DeclareUnit["acre", Unit["Acre"], TraditionalLabel -> "acre",   CreateSymbol -> False], (**)
 DeclareUnit["acre_ft", Unit["Acre"] Unit["Foot"],   TraditionalLabel -> "acre\[CenterDot]ft", CreateSymbol -> False], (**)
 DeclareUnit["angstrom", Unit["Angstrom"],   TraditionalLabel -> "Angstrom", CreateSymbol -> False], (**)
 DeclareUnit["angular_frequency", Unit["Circle"]/Unit["Second"],   TraditionalLabel -> "Hza", CreateSymbol -> False], (**)
 DeclareUnit["atmosphere", Unit["Atmosphere"],   TraditionalLabel -> "atm", CreateSymbol -> False],  (**)
 DeclareUnit["bar", Unit["Bar"], TraditionalLabel -> "bar",   CreateSymbol -> False], (**)
 DeclareUnit["barn", Unit["Barn"], TraditionalLabel -> "barn",   CreateSymbol -> False], (**)
 DeclareUnit["barye", Unit["Barye"], TraditionalLabel -> "barye",   CreateSymbol -> False], (**)
 DeclareUnit["base_currency", Unit["base_currency"],   CreateSymbol -> False], 
 DeclareUnit["becquerel", Unit["Becquerel"], TraditionalLabel -> "Bq",   CreateSymbol -> False], (**)
 DeclareUnit["bohr", Unit[52.9177*10^-12, "Meter"], TraditionalLabel -> "a.0",   CreateSymbol -> False], 
 DeclareUnit["boiler_horsepower", Unit[33 479,"BTU"],   TraditionalLabel -> "bhp", CreateSymbol -> False], (**)
 DeclareUnit["calorie", Unit["Calorie"], TraditionalLabel -> "cal",   CreateSymbol -> False], (**)
 DeclareUnit["Canadian_BTU", Unit[1/1.000418022, "BTU"],   TraditionalLabel -> "CBTU", CreateSymbol -> False], (**)
 DeclareUnit["candela", Unit["Candela"], TraditionalLabel -> "cd",   CreateSymbol -> False], (**)
 DeclareUnit["centimeter", Unit["Centimeter"],   TraditionalLabel -> "cm", CreateSymbol -> False], 	(**)
 DeclareUnit["cubic_feet_per_minute", Unit["Foot"]^3/Unit["Minute"],   TraditionalLabel -> "cfm", CreateSymbol -> False],	 	(**)
 DeclareUnit["cubit", Unit["Cubit"], TraditionalLabel -> "cubit",   CreateSymbol -> False], (**)
 DeclareUnit["degree", Unit["Degree"],   TraditionalLabel -> "\[Degree]", CreateSymbol -> False], (**)
 DeclareUnit["deltaC", Unit["deltaC"],   TraditionalLabel -> "\[CapitalDelta]\[Degree]C",   CreateSymbol -> False], 
 DeclareUnit["deltaF", Unit["deltaF"],   TraditionalLabel -> "\[CapitalDelta]\[Degree]F",   CreateSymbol -> False], 
 DeclareUnit["dietetic_calorie", Unit["dietetic_calorie"],   TraditionalLabel -> "dcal", CreateSymbol -> False], 
 DeclareUnit["dpi", Unit[1,1/"Inch"], TraditionalLabel -> "dpi",   CreateSymbol -> False], (**)
 DeclareUnit["electric_horsepower", Unit["electric_horsepower"],   TraditionalLabel -> "ehp", CreateSymbol -> False], 
 DeclareUnit["epsilon0", Unit[8.85*10^-12,"Farad"/"Meter"],   TraditionalLabel -> "\[CurlyEpsilon].0", CreateSymbol -> False], (**)
 DeclareUnit["erg", Unit["Erg"], TraditionalLabel -> "erg",   CreateSymbol -> False], (**)
 DeclareUnit["fluid_ounce", Unit["FluidOunce"],   TraditionalLabel -> "fl_oz", CreateSymbol -> False], (**)
 DeclareUnit["foot", Unit["Foot"], TraditionalLabel -> "ft",   CreateSymbol -> False], (**)
 DeclareUnit["foot_kip", Unit["Foot"] Unit["kip"],   TraditionalLabel -> "ft\[CenterDot]kip", CreateSymbol -> False], (**)
 DeclareUnit["foot_pound", Unit["Foot"] Unit["Pound"],   TraditionalLabel -> "ft\[CenterDot]lbf", CreateSymbol -> False], (**)
 DeclareUnit["fortnight", 2 Unit["Week"],   TraditionalLabel -> "fortnight", CreateSymbol -> False], (**)
 DeclareUnit["furlong", Unit["Furlong"],   TraditionalLabel -> "furlong", CreateSymbol -> False], (**)
 DeclareUnit["gallon", Unit["Gallon"], TraditionalLabel -> "gal",   CreateSymbol -> False], (**)
 DeclareUnit["gallons_per_minute", Unit["Gallon"]/Unit["Minute"],   TraditionalLabel -> "gpm", CreateSymbol -> False], (**)
 DeclareUnit["gigahertz", Unit["Gigahertz"],   TraditionalLabel -> "GHz", CreateSymbol -> False], (**)
 DeclareUnit["giganewton", Unit["Giganewton"],   TraditionalLabel -> "GN", CreateSymbol -> False], (**)
 DeclareUnit["gigapascal", Unit["Gigapascal"],   TraditionalLabel -> "GPa", CreateSymbol -> False], (**)
 DeclareUnit["gram", Unit["Gram"], TraditionalLabel -> "gm",   CreateSymbol -> False], (**)
 DeclareUnit["gravitational_acceleration",   Unit[9.81 "Meter"/"Second"], TraditionalLabel -> "g",   CreateSymbol -> False],  (**)
 DeclareUnit["gray", Unit["Gray"], TraditionalLabel -> "Gy",   CreateSymbol -> False], (**)
 DeclareUnit["hertz", Unit["Hertz"], TraditionalLabel -> "Hz",   CreateSymbol -> False], (**)
 DeclareUnit["horsepower", Unit["Horsepower"],   TraditionalLabel -> "hp", CreateSymbol -> False], (**)
 DeclareUnit["inch", Unit["Inch"], TraditionalLabel -> "in",   CreateSymbol -> False], (**)
 DeclareUnit["inches_mercury", Unit["InchesMercury"],   TraditionalLabel -> "in_Hg", CreateSymbol -> False], (**)
 DeclareUnit["inch_kip", Unit["Inch"] Unit["kip"],   TraditionalLabel -> "in\[CenterDot]kip", CreateSymbol -> False], (**)
 DeclareUnit["inch_ounce", Unit["Inch"]Unit["Ounce"],   TraditionalLabel -> "in\[CenterDot]ozf", CreateSymbol -> False], (**)
 DeclareUnit["inch_pound", Unit["Inch"] Unit["Pound"],   TraditionalLabel -> "in\[CenterDot]lbf", CreateSymbol -> False], (**)
 DeclareUnit["International_BTU", Unit[1055.05585262,"Joule"],   TraditionalLabel -> "Btu", CreateSymbol -> False], (**)
 DeclareUnit["ISO_BTU", Unit[1055.056, "Joule"], TraditionalLabel -> "IBTU",   CreateSymbol -> False], (**)
 DeclareUnit["katal", Unit[6.0221417930*^23/"Second"], TraditionalLabel -> "katal",   CreateSymbol -> False], (**)
 DeclareUnit["kelvin", Unit["Kelvin"], TraditionalLabel -> "K",   CreateSymbol -> False], (**)
 DeclareUnit["kiloampere", Unit["Kiloampere"],   TraditionalLabel -> "kA", CreateSymbol -> False], (**)
 DeclareUnit["kilocalorie", Unit[1000,"Calorie"],   TraditionalLabel -> "kcal", CreateSymbol -> False], (**)
 DeclareUnit["kilogram", Unit["Kilogram"], TraditionalLabel -> "kg",   CreateSymbol -> False], (**)
 DeclareUnit["kilogram_force", Unit["KilogramForce"],   TraditionalLabel -> "kgf", CreateSymbol -> False], (**)
 DeclareUnit["kilohertz", Unit["Kilohertz"],   TraditionalLabel -> "kHz", CreateSymbol -> False], (**)
 DeclareUnit["kilometer", Unit["Kilometer"], TraditionalLabel -> "km",   CreateSymbol -> False], (**)
 DeclareUnit["kilonewton", Unit["Kilonewton"],   TraditionalLabel -> "kN", CreateSymbol -> False], (**)
 DeclareUnit["kiloNewton_centimeter", Unit["Kilonewton"] Unit["Centimeter"],   TraditionalLabel -> "kN\[CenterDot]cm", CreateSymbol -> False], (**)
 DeclareUnit["kiloNewton_meter", Unit["Kilonewton"] Unit["Meter"],   TraditionalLabel -> "kN\[CenterDot]m", CreateSymbol -> False], (**)
 DeclareUnit["kilopascal", Unit["Kilopascal"],   TraditionalLabel -> "kPa", CreateSymbol -> False], (**)
 DeclareUnit["kilovolt", Unit["Kilovolt"], TraditionalLabel -> "kV",   CreateSymbol -> False], (**)
 DeclareUnit["kilowatt", Unit["Kilowatt"], TraditionalLabel -> "kW",   CreateSymbol -> False], (**)
 DeclareUnit["kip", Unit[4448.222,"Newton"], TraditionalLabel -> "kip",   CreateSymbol -> False], (**)
 DeclareUnit["kips_per_sq_foot", Unit["kip"/"Foot"^2],   TraditionalLabel -> "ksf", CreateSymbol -> False], (**)
 DeclareUnit["kips_per_sq_inch", Unit["kip"/"Inch"^2],   TraditionalLabel -> "ksi", CreateSymbol -> False], (**)
 DeclareUnit["knots", Unit["Knot"], TraditionalLabel -> "knot",   CreateSymbol -> False], (**)
 DeclareUnit["liter", Unit["Liter"], TraditionalLabel -> "L",   CreateSymbol -> False], (**)
 DeclareUnit["lumen", Unit["Lumen"], TraditionalLabel -> "lm",   CreateSymbol -> False], (**)
 DeclareUnit["lux", Unit["Lux"], TraditionalLabel -> "lx",   CreateSymbol -> False], (**)
 DeclareUnit["magnitude_speed_of_light",   Unit[299792458, "Meter"/"Second"], TraditionalLabel -> "c_",   CreateSymbol -> False], (**)
 DeclareUnit["maxwell", Unit["Maxwell"], TraditionalLabel -> "Mx",   CreateSymbol -> False], (**)
 DeclareUnit["mean_BTU", Unit[1055.87,"Joule"], TraditionalLabel -> "mBTU",   CreateSymbol -> False], (**)
 DeclareUnit["mean_calorie", Unit[4.190, "Joule"],   TraditionalLabel -> "mcal", CreateSymbol -> False], (**)
 DeclareUnit["mega_gallons_per_day", 10^6 Unit["Gallons"] Unit["Day"],   TraditionalLabel -> "mgd", CreateSymbol -> False], (**)
 DeclareUnit["megahertz", Unit["Megahertz"],   TraditionalLabel -> "MHz", CreateSymbol -> False], (**)
 DeclareUnit["meganewton", Unit["Meganewton"],   TraditionalLabel -> "MN", CreateSymbol -> False], (**)
 DeclareUnit["megaohm", Unit["Megaohm"],   TraditionalLabel -> "M\[CapitalOmega]", CreateSymbol -> False], (**)
 DeclareUnit["megapascal", Unit["Megapascal"],   TraditionalLabel -> "MPa", CreateSymbol -> False], (**)
 DeclareUnit["megawatt", Unit["Megawatt"], TraditionalLabel -> "MW",   CreateSymbol -> False], (**)
 DeclareUnit["meter", Unit["Meter"], TraditionalLabel -> "m",   CreateSymbol -> False], (**)
 DeclareUnit["microampere", Unit["Microampere"],   TraditionalLabel -> "\[Mu]A", CreateSymbol -> False], (**)
 DeclareUnit["microcoulomb", Unit["Microcoulomb"],   TraditionalLabel -> "\[Mu]C", CreateSymbol -> False], (**)
 DeclareUnit["microfarad", Unit["Microfarad"],   TraditionalLabel -> "\[Mu]F", CreateSymbol -> False], (**)
 DeclareUnit["microhenry", Unit["Microhenry"],   TraditionalLabel -> "\[Mu]H", CreateSymbol -> False], (**)
 DeclareUnit["micron", Unit["Micron"], TraditionalLabel -> "\[Mu]m",   CreateSymbol -> False], (**)
 DeclareUnit["microsecond", Unit["Microsecond"],   TraditionalLabel -> "\[Mu]s", CreateSymbol -> False], (**)
 DeclareUnit["microvolt", Unit["Microvolt"],   TraditionalLabel -> "\[Mu]V", CreateSymbol -> False], (**)
 DeclareUnit["microwatt", Unit["Microwatt"],   TraditionalLabel -> "\[Mu]W", CreateSymbol -> False], (**)
 DeclareUnit["mil", Unit["Mil"], TraditionalLabel -> "mil",   CreateSymbol -> False], (**)
 DeclareUnit["mile", Unit["Mile"], TraditionalLabel -> "mi",   CreateSymbol -> False], (**)
 DeclareUnit["miles_per_hour", Unit["Mile"]/Unit["Hour"],   TraditionalLabel -> "mph", CreateSymbol -> False], (**)
 DeclareUnit["milliampere", Unit["Milliampere"],   TraditionalLabel -> "mA", CreateSymbol -> False], (**)
 DeclareUnit["millicoulomb", Unit["Millicoulomb"],   TraditionalLabel -> "mC", CreateSymbol -> False], (**)
 DeclareUnit["milligram", Unit["Milligram"], TraditionalLabel -> "mg",   CreateSymbol -> False], (**)
 DeclareUnit["millihenry", Unit["Millihenry"],   TraditionalLabel -> "mH", CreateSymbol -> False], (**)
 DeclareUnit["milliliter", Unit["Milliliter"],   TraditionalLabel -> "mL", CreateSymbol -> False], (**)
 DeclareUnit["millimeter", Unit["Millimeter"],   TraditionalLabel -> "mm", CreateSymbol -> False], (**)
 DeclareUnit["millisecond", Unit["Millisecond"],   TraditionalLabel -> "ms", CreateSymbol -> False], (**)
 DeclareUnit["millivolt", Unit["Millivolt"], TraditionalLabel -> "mV",   CreateSymbol -> False], (**)
 DeclareUnit["milliwatt", Unit["Milliwatt"], TraditionalLabel -> "mW",   CreateSymbol -> False], (**)
 DeclareUnit["minute", Unit["Minute"], TraditionalLabel -> "min",   CreateSymbol -> False], (**)
 DeclareUnit["mole", Unit["Mole"], TraditionalLabel -> "mol",   CreateSymbol -> False], 
 DeclareUnit["mu0", Unit["mu0"], TraditionalLabel -> "\[Mu].0",   CreateSymbol -> False], 
 DeclareUnit["nanoampere", Unit["Nanoampere"],   TraditionalLabel -> "nA", CreateSymbol -> False], (**)
 DeclareUnit["nanocoulomb", Unit["Nanocoulomb"],   TraditionalLabel -> "nC", CreateSymbol -> False], (**)
 DeclareUnit["nanofarad", Unit["Nanofarad"], TraditionalLabel -> "nF",   CreateSymbol -> False], (**)
 DeclareUnit["nanometer", Unit["Nanometer"], TraditionalLabel -> "nm",   CreateSymbol -> False], (**)
 DeclareUnit["nanosecond", Unit["Nanosecond"],   TraditionalLabel -> "ns", CreateSymbol -> False], (**)
 DeclareUnit["nanovolt", Unit["Nanovolt"], TraditionalLabel -> "nV",   CreateSymbol -> False], (**)
 DeclareUnit["nanowatt", Unit["Nanowatt"], TraditionalLabel -> "nW",   CreateSymbol -> False], (**)
 DeclareUnit["nautical_mile", Unit["NauticalMile"],   TraditionalLabel -> "nmi", CreateSymbol -> False], (**)
 DeclareUnit["Newton_centimeter", Unit["Newton"] Unit["Centimeter"],   TraditionalLabel -> "N\[CenterDot]cm", CreateSymbol -> False], (**)
 DeclareUnit["Newton_meter", Unit["Newton"] Unit["Meter"],   TraditionalLabel -> "N\[CenterDot]m", CreateSymbol -> False], (**)
 DeclareUnit["Newton_millimeter", Unit["Newton"]Unit["Millimeter"],   TraditionalLabel -> "N\[CenterDot]mm", CreateSymbol -> False], (**)
 DeclareUnit["oersted", Unit["Oersted"], TraditionalLabel -> "Oe",   CreateSymbol -> False], (**)
 DeclareUnit["ohm", Unit["Ohm"],   TraditionalLabel -> "\[CapitalOmega]", CreateSymbol -> False], (**)
 DeclareUnit["ounce", Unit["Ounce"], TraditionalLabel -> "oz",   CreateSymbol -> False], (**)
 DeclareUnit["ounce_force", Unit["ounce_force"],   TraditionalLabel -> "ozf", CreateSymbol -> False], 
 DeclareUnit["pascal", Unit["Pascal"], TraditionalLabel -> "Pa",   CreateSymbol -> False], (**)
 DeclareUnit["picocoulomb", Unit["Picocoulomb"],   TraditionalLabel -> "pC", CreateSymbol -> False], (**)
 DeclareUnit["picofarad", Unit["Picofarad"], TraditionalLabel -> "pF",   CreateSymbol -> False], (**)
 DeclareUnit["picompere", Unit["Picompere"], TraditionalLabel -> "pA",   CreateSymbol -> False], (**)
 DeclareUnit["picosecond", Unit["Picosecond"],   TraditionalLabel -> "ps", CreateSymbol -> False], (**)
 DeclareUnit["picovolt", Unit["Picovolt"], TraditionalLabel -> "pV",   CreateSymbol -> False], (**)
 DeclareUnit["picowatt", Unit["Picowatt"], TraditionalLabel -> "pW",   CreateSymbol -> False], (**)
 DeclareUnit["pound", Unit["Pound"], TraditionalLabel -> "lb",   CreateSymbol -> False], (**)
 DeclareUnit["pound_force", Unit["PoundForce"],   TraditionalLabel -> "lbf", CreateSymbol -> False], (**)
 DeclareUnit["pounds_per_cubic_foot", Unit["PoundForce"]/Unit["Foot"]^3,   TraditionalLabel -> "pcf", CreateSymbol -> False], (**)
 DeclareUnit["pounds_per_cubic_inch", Unit["PoundForce"]/Unit["Inch"]^3,   TraditionalLabel -> "pci", CreateSymbol -> False], (**)
 DeclareUnit["pounds_per_sq_foot", Unit["PoundForce"]/Unit["Foot"]^2,   TraditionalLabel -> "psf", CreateSymbol -> False], (**)
 DeclareUnit["pounds_per_sq_inch", Unit["PSI"],   TraditionalLabel -> "psi", CreateSymbol -> False], (**)
 DeclareUnit["radian", Unit["Radian"], TraditionalLabel -> "rad",   CreateSymbol -> False], (**)
 DeclareUnit["rankine", Unit["Rankine"], TraditionalLabel -> "R",   CreateSymbol -> False], (**)
 DeclareUnit["revolution", Unit["Circle"],   TraditionalLabel -> "rev", CreateSymbol -> False], 
 DeclareUnit["revolutions_per_minute", Unit["revolution"]/Unit["Minute"],   TraditionalLabel -> "rpm", CreateSymbol -> False], (**)
 (*DeclareUnit["siemens", Unit["siemens"], TraditionalLabel -> "mho",   CreateSymbol -> False], *)
 DeclareUnit["siemens", Unit["Siemens"],   TraditionalLabel -> "siemens", CreateSymbol -> False], (**)
 DeclareUnit["sievert", Unit["Sievert"], TraditionalLabel -> "Sv",   CreateSymbol -> False], (**)
 DeclareUnit["slug", Unit["Slug"], TraditionalLabel -> "slug",   CreateSymbol -> False], (**)
 DeclareUnit["smoot", Unit[1.70180,"Meter"], TraditionalLabel -> "Smoot",   CreateSymbol -> False], 
 DeclareUnit["speed_of_light", Unit[299792458, "Meter"/"Second"],   TraditionalLabel -> "c", CreateSymbol -> False], (**)
 DeclareUnit["statcoulomb", Unit["Statcoulomb"],   TraditionalLabel -> "esu", CreateSymbol -> False], (**)
 DeclareUnit["stokes", Unit["Stokes"], TraditionalLabel -> "stokes",   CreateSymbol -> False], (**)
 DeclareUnit["teranewton", Unit["Teranewton"],   TraditionalLabel -> "TN", CreateSymbol -> False], (**)
 DeclareUnit["thermochemical_BTU", Unit[1054.35026444,"Joule"],   TraditionalLabel -> "tBTU", CreateSymbol -> False], (**)
 DeclareUnit["thermochemical_calorie", Unit[4.184,"Joule"],   TraditionalLabel -> "tcal", CreateSymbol -> False], (**)
 DeclareUnit["ton_force", Unit["TonForce"],   TraditionalLabel -> "tonf", CreateSymbol -> False], (**)
 DeclareUnit["tonne_force", Unit[50000000/45359237, "TonForce"],   TraditionalLabel -> "tonnef", CreateSymbol -> False], (**)
 DeclareUnit["torr", Unit["Torr"], TraditionalLabel -> "torr",   CreateSymbol -> False], (**)
 DeclareUnit["UK_gallon", Unit["UK_gallon"],   TraditionalLabel -> "galUK", CreateSymbol -> False], 
 DeclareUnit["UK_horsepower", Unit["UK_horsepower"],   TraditionalLabel -> "hpUK", CreateSymbol -> False], 
 DeclareUnit["water_horsepower", Unit["water_horsepower"],   TraditionalLabel -> "hhp", CreateSymbol -> False], 
 DeclareUnit["weber", Unit["Weber"], TraditionalLabel -> "Wb",   CreateSymbol -> False], (**)
 DeclareUnit["yard", Unit["Yard"], TraditionalLabel -> "yd",   CreateSymbol -> False], (**)
 DeclareUnit["degC", Unit["Centigrade"], TraditionalLabel -> "\[Degree]C",   CreateSymbol -> False], (**)
 DeclareUnit["degF", Unit["Fahrenheit"], TraditionalLabel -> "\[Degree]F",   CreateSymbol -> False] (**)
 (*Probably time format conversion
 DeclareUnit["hhmmss", Unit["hhmmss"], TraditionalLabel -> "hhmmss",   CreateSymbol -> False]*)
 };