UnitSet["MKS"]={Unit[1, "Meter"], Unit[1, "Meter"^2], Unit[1, "Meter"^3], 
 Unit[1, "Meter"^(-1)], 
   Unit[1, "Kilogram"], Unit[1, "Second"], Unit[1, "Second"^(-1)], 
   Unit[1, "Meter"/"Second"], 
 Unit[1, ("Kilogram"*"Meter")/"Second"^2], 
   Unit[1, ("Kilogram"*"Meter"^2)/"Second"^2], 
   Unit[1, ("Kilogram"*"Meter"^2)/"Second"^3], 
   Unit[1, "Kilogram"/("Meter"*"Second"^2)], 
 Unit[1, "Kilogram"/("Meter"*"Second")], 
   Unit[1, "Ampere"*"Second"], Unit[1, "Ampere"], 
   Unit[1, ("Kilogram"*"Meter"^2)/("Ampere"*"Second"^3)], 
   Unit[1, ("Kilogram"*"Meter")/("Ampere"*"Second"^3)], 
   Unit[1, ("Kilogram"*"Meter"^2)/("Ampere"*"Second"^2)], 
   Unit[1, ("Kilogram"*"Meter"^4)/("Ampere"*"Second"^2)], 
 Unit[1, "Ampere"/"Meter"], 
   Unit[1, "Ampere"*"Meter"^2], Unit[1, ("Kilogram"*"Meter"^2)/
       ("Ampere"^2*"Second"^3)], 
 Unit[1, ("Kilogram"*"Meter"^3)/("Ampere"^2*"Second"^3)], 
   Unit[1, ("Ampere"^2*"Second"^4)/("Kilogram"*"Meter"^2)], 
   Unit[1, ("Kilogram"*"Meter"^2)/("Ampere"^2*"Second"^2)], 
 Unit[1, "Radian"], 
   Unit[1, "Kelvin"], Unit[1, ("Kelvin"*"Second"^3)/"Kilogram"],Unit["Bit"]};