UnitSet["Swedish"]={(*Length*)
	DeclareUnit["Aln",Unit[0.539,"Meter"],UsageMessage->"Aln is a Swedish unit of length."],
	DeclareUnit["Famn",Unit[3,"Aln"],UsageMessage->"Famn is a Swedish unit of length."],
	DeclareUnit["SwedishKvarter",Unit[1/4,"Aln"],UsageMessage->"SwedishKvarter is a Swedish unit of length.",TraditionalLabel->"Kvarter"],	
	DeclareUnit["SwedishFot",Unit[1/2,"Aln"],UsageMessage->"SwedishFot is a Swedish unit of length.",TraditionalLabel->"Fot"],	
	DeclareUnit["Tum",Unit[1/10,"SwedishFot"],UsageMessage->"Tum is a Swedish unit of length."],	
	DeclareUnit["SwedishLinje",Unit[1/10,"Tum"],UsageMessage->"SwedishLinje is a Swedish unit of length.",TraditionalLabel->"Linje"],	
	DeclareUnit["SwedishMil",Unit[10000,"Meter"],UsageMessage->"SwedishMil is a Swedish unit of length.",TraditionalLabel->"Mil"],	
	DeclareUnit["Nymil",Unit[1,"SwedishMil"],UsageMessage->"Nymil is a Swedish unit of length."],	
	DeclareUnit["Kyndemil",Unit[16000.,"Meter"],UsageMessage->"Kyndemil is a Swedish approximate unit of length."],	
	DeclareUnit["Skogsmil",Unit[5000.,"Meter"],UsageMessage->"Skogsmil is a Swedish approximate unit of length."],	
	DeclareUnit["Stenkast",Unit[50.,"Meter"],UsageMessage->"Stenkast is a Swedish approximate unit of length."],
	DeclareUnit["Fjardingsvag",Unit[1/4,"Mil"],UsageMessage->"Fjardingsvag is a Swedish unit of length."],	
	DeclareUnit["Ref",Unit[100,"SwedishFot"],UsageMessage->"Ref is a Swedish unit of length."],		
	DeclareUnit["SwedishStang",Unit[16,"SwedishFot"],UsageMessage->"SwedishStang is a Swedish unit of length.",TraditionalLabel->"Stang"],	
	DeclareUnit["Tvarhand",Unit[16,"Inch"],UsageMessage->"Tvarhand is a Swedish unit of length."],	
	DeclareUnit["Kabellangd",Unit[1/10,"NauticalMile"],UsageMessage->"Kabellangd is a Swedish unit of nautical distance."],	
	DeclareUnit["SwedishKvartmil",Unit["NauticalMile"],UsageMessage->"SwedishKvartmil is a Swedish unit of nautical distance.",TraditionalLabel->"Kvartmil"],
	DeclareUnit["SwedishSjomil",Unit[4,"SwedishKvartmil"],UsageMessage->"SwedishSjomil is a Swedish unit of nautical distance.",TraditionalLabel->"Sjomil"],
 (*Area*)
	DeclareUnit["Kannaland",1000 Unit["SwedishFot"]^2,UsageMessage->"Kannaland  is a Swedish unit of area."],
	DeclareUnit["Kappland",153.4 Unit["Meter"]^2,UsageMessage->"Kappland  is a Swedish unit of area."],
	DeclareUnit["Spannland",Unit[16 ,"Kappland"],UsageMessage->"Spannland  is a Swedish unit of area."],
	DeclareUnit["Tunnland",1000 Unit[2,"Spannland"],UsageMessage->"Tunnland  is a Swedish unit of area."],
	DeclareUnit["Kvadratmil",Unit["Mil"]^2,UsageMessage->"Kvadratmil  is a Swedish unit of area."],
	(*Volume*)
	DeclareUnit["Pot",Unit[0.966,"Liter"],UsageMessage->"Pot is a Swedish unit of volume."],
	DeclareUnit["Ankare",Unit[39.26,"Liter"],UsageMessage->"Ankare is a Swedish unit of volume."],
	DeclareUnit["SwedishOhm",Unit[155,"Pot"],UsageMessage->"SwedishOhm is a Swedish unit of volume."],
	DeclareUnit["Storfavn",3.77 Unit["Meter"]^3,UsageMessage->"Storfavn is a Swedish unit of volume."],	
	DeclareUnit["Kubikkfavn",5.85 Unit["Meter"]^3,UsageMessage->"Kubikkfavn is a Swedish unit of volume."],		
	 (*Mass*)
	DeclareUnit["Skalpund", Unit[0.42507,"Kilogram"],UsageMessage->"Skalpund is a Swedish unit of mass."],	
	DeclareUnit["Lispund", Unit[20,"Skalpund"],UsageMessage->"Lispund is a Swedish unit of mass."],
	DeclareUnit["SwedishBismerpund", Unit[12,"Skalpund"],UsageMessage->"SwedishBismerpund is a Swedish unit of mass."],
	DeclareUnit["Skeppspund", Unit[20,"Lispund"],UsageMessage->"Skeppspund is a Swedish unit of mass."],
	DeclareUnit["Mark", Unit[1/2,"Skalpund"],UsageMessage->"Mark is a Swedish unit of mass."],
	DeclareUnit["SwedishOrt", Unit[4.2508,"Gram"],UsageMessage->"SwedishOrt is a Swedish unit of mass."]
	};
