(* Mathematica Test File *)

TestSuite[
    {
    "MASSmodelRelatedTests.mt"
    ,
    "ReactionRelatedTests.mt" 
    ,
    "MetaboliteRelatedTests.mt"
    ,
    "EquationConstructionRelatedTests.mt"
    ,
    "ParameterRelatedTests.mt"
    ,
    "SensitivityAnalysisRelatedTests.mt"
    ,
    "UtilityRelatedTests.mt"
    ,
    "SimulationRelatedTests.mt"
    ,
    "ChemoInformaticsRelatedTests.mt"
    ,
    "QcQaRelatedTests.mt"
    ,
    "CobraRelatedTests.mt"
    ,
    "GPRRelatedTests.mt"
    (*,
    "SBMLrelatedTests.mt"*)
   	,
    "UnitCheckingRelatedTests.mt"
    ,
    "ThermodynamicsTests.mt"
   }
]